### ISSUE TITLE
Failed to create the Debian package ... bitcoinprivate-desktop-gui-wallet_0.0.1_all.deb

### ISSUE THREAD

**Issue by jmuchaxo** [BTCPrivate/bitcoin-private-full-node-wallet#10]
Hello, I get this error with ant compilation,
thank you

 ant -buildfile ./src/build/build.xml
... 
Creating debian package: /home/joaquim/bitcoin-private-full-node-wallet/build/ubuntu-package/bitcoinprivate-desktop-gui-wallet_0.0.1_all.deb
      [deb] Building data
      [deb] file:./usr/lib/bitcoinprivate-gui-wallet/BitcoinPrivateDesktopWallet.jar size:578851 mode:493 linkname: username:root userid:0 groupname:root groupid:0 modtime:Sat Mar 03 17:38:33 WET 2018 md5: 0b663b2d3885b7dd250940afc356a4d4
      [deb] file:./usr/lib/bitcoinprivate-gui-wallet/bitcoinj-core-0.14.5.jar size:1570589 mode:493 linkname: username:root userid:0 groupname:root groupid:0 modtime:Sat Mar 03 17:38:34 WET 2018 md5: e78d7b264743d2df01be7f65ac794f91
      [deb] file:./usr/lib/bitcoinprivate-gui-wallet/bitcoinj-core-0.14.5_LICENSE.txt size:11361 mode:493 linkname: username:root userid:0 groupname:root groupid:0 modtime:Sat Mar 03 17:38:34 WET 2018 md5: d8927f3331d2b3e321b7dd1925166d25
      [deb] file:./usr/lib/bitcoinprivate-gui-wallet/sqlite-jdbc-3.21.0.jar size:6672489 mode:493 linkname: username:root userid:0 groupname:root groupid:0 modtime:Sat Mar 03 17:38:34 WET 2018 md5: 349c1f4700debe796466f9b321f64aa0
      [deb] file:./usr/lib/bitcoinprivate-gui-wallet/sqlite-jdbc-3.21.0_LICENSE.txt size:12674 mode:493 linkname: username:root userid:0 groupname:root groupid:0 modtime:Sat Mar 03 17:38:34 WET 2018 md5: d03afd2e342fa9f70d1aadb08b6a5f3a
      [deb] file:./usr/bin/bitcoinprivate-desktop-gui-wallet size:1792 mode:493 linkname: username:root userid:0 groupname:root groupid:0 modtime:Sat Mar 03 17:38:34 WET 2018 md5: 04e2afc5a0061d77912adb4aeff9bfb2
      [deb] file:./usr/share/applications/BitcoinPrivateWallet.desktop size:388 mode:493 linkname: username:root userid:0 groupname:root groupid:0 modtime:Sat Mar 03 17:38:34 WET 2018 md5: b6cdadc44d9b56cc14e0be792741edc7
      [deb] Failed to create the Debian package /home/joaquim/bitcoin-private-full-node-wallet/build/ubuntu-package/bitcoinprivate-desktop-gui-wallet_0.0.1_all.deb

BUILD FAILED

**Comment by mosh5382** [comment]
I am having the same issue on Arch Linux.

**Comment by jmuchaxo** [comment]
yes the wallet jar file is there.
I should have payed attention, thanks
