### ISSUE TITLE
Workaround: Unable to send on OS High Sierra

### ISSUE THREAD

**Issue by SpencerBoyd** [BTCPrivate/bitcoin-private-full-node-wallet#10]
So I've had the following issue when trying to send from the full node wallet to the electrum wallet (or any outside wallet).
<img width="659" alt="screen shot 2018-03-11 at 1 30 36 pm" src="https://user-images.githubusercontent.com/7565676/37258153-8a833e4c-2530-11e8-8158-b5af71f80ad7.png">

I found a workaround that enables sending:
First, you copy an address from the Full Node wallet and paste that into the Destination address box. 
Next, delete everything except the "b1" at the beginning. 
Then, copy and paste in the electrum or exchange destination address minus the "b1". 
After this, the full node wallet will recognize the address as valid and send as intended. 

Not sure why this works but if anyone else has this issue, this is working for now!

**Comment by ch4ot1c** [comment]
This is because you need to upgrade your version to the latest release. Only send directly to addresses you intend to, please~!

**Comment by SpencerBoyd** [comment]
This error is occurring with the latest release. I am sending to addresses I intend to, the wallet is not acting as intended. I shouldn’t have to collage addresses together in order for the wallet to recognize it as valid. Clearly there is something wrong with the wallet determining valid destination addresses. I created this issue so that you guys could have more info to solve the problem, not so you can just dismiss me.

**Comment by lukevenediger** [comment]
@ch4ot1c with respect, @SpencerBoyd has followed this elaborate workaround **because** the latest release is not working. I'm in the same position and would prefer to have a functioning release than do this. Please see issue #5
