### ISSUE TITLE
Version 1.0.1 shows old version in UI

### ISSUE THREAD

**Issue by vienie** [BTCPrivate/bitcoin-private-full-node-wallet#16]
In the Bitcoin Private Desktop GUI Wallet's UI of version 1.0.1 it still shows up as version 1.0.0 in the top bar. Correct version is shown in about us dialog box.  This is on the Mac version

**Comment by ch4ot1c** [comment]
This is known ; the patched release was done with haste. Will be fixed in an official 1.0.2.

**Comment by Pega88** [comment]
fixed with https://github.com/BTCPrivate/bitcoin-private-full-node-wallet/commit/809234c579bf681000f9c6adb8cb13d08fad3359
should be more streamlined in future.
