### ISSUE TITLE
'0 connections' is just too scary

### ISSUE THREAD

**Issue by ch4ot1c** [BTCPrivate/bitcoin-private-full-node-wallet#20]
The red 0 connections in the status is not a good user experience. It should definitely be clear that it has a high change of finding peers in the next 15s-1min.

**Comment by agzamishe** [comment]
Same problem

**Comment by Pega88** [comment]
fixed with https://github.com/BTCPrivate/bitcoin-private-full-node-wallet/commit/217a2a3121f8b5f3a7dc44a138ebcea436166255
