### ISSUE TITLE
Remind users the benefits of running a full-node

### ISSUE THREAD

**Issue by ch4ot1c** [BTCPrivate/bitcoin-private-full-node-wallet#21]
Add a UI element that tells users 'If you are fully syncd, you **are** Bitcoin Private.' - or more informational detail.

**Comment by Pega88** [comment]
fixed with https://github.com/BTCPrivate/bitcoin-private-full-node-wallet/commit/0a0692f3a2929f8de84c604d68cd92da4babb8ee
