### ISSUE TITLE
There are no transactions involving this address.

### ISSUE THREAD

**Issue by noobcrypto** [BTCPrivate/bitcoin-private-full-node-wallet#24]
sent btcp from one wallet to another. it's been 24+ hours  i see this in block chain explorer There are no transactions involving this address.

**Comment by BlueSilver22** [comment]
@noobcrypto what is percentage synced are you on the wallet?

**Comment by noobcrypto** [comment]
Thanks for getting back I'm at 100% sync

**Comment by noobcrypto** [comment]
I have my private keys

**Comment by donshin** [comment]
@noobcrypto I recommend seeking more hands-on help in the #help channel for the official Bitcoin Private Discord server.

**Comment by Pega88** [comment]
I follow @donshin's comment, please use the help channels. You can reopen if you find a way to reproduce this, as now it doesn't really seem related to the wallet.
