### ISSUE TITLE
Destination address does not appear to be a valid BTCP address

### ISSUE THREAD

**Issue by kornface13** [BTCPrivate/bitcoin-private-full-node-wallet#27]
Sent a test transaction successfully.  Used the same address to send another transaction and it says 

The destination address to send BTCP to:
b1NXz11SNmpZPdeQEkYu134p22F8beqboex 
does not appear to be a valid BTCP address.  BTCP addresses start with b1, bx or zk!

Its a valid address: https://explorer.btcprivate.org/address/b1NXz11SNmpZPdeQEkYu134p22F8beqboex

**Comment by donshin** [comment]
@kornface13 Can you confirm the version number of the build you are using?

**Comment by spuky** [comment]
had same Issue here... trying to sending to my ledger nano s was happening with 1.0.3 and 1.0.4 on OSX was trying multible addresses from the electrum wallet ( P!1.1.0 osx ) all failed... then i tried copy one address into textedit and from there to the Desktop wallet it worked... 
Confirmed that with a second address...

so maybe there is getting more none printable stuff into the clipboard when using the electrum 
wallet... and it is more an issue of the electrum wallet putting aditional stuff into the clipboard

electrum wallet Clipbord information:
![clipboard_viewer_und_spuky](https://user-images.githubusercontent.com/271187/39013325-556fd6f6-4417-11e8-90c3-c9bb5f00623b.jpg)


Textedit Clipbord information:
![clipboard_viewer](https://user-images.githubusercontent.com/271187/39013243-17a34fec-4417-11e8-967c-ef20933f0de8.jpg)


Screenshots taken from.. clipboard viewer: 
https://developer.apple.com/library/content/samplecode/ClipboardViewer/Introduction/Intro.html

Hope that helps... won't decide if it is the Desktop wallet parsing the clipboard wrong.. or electrum wallte filling it wrong....

Workarround is to go over a simple texteditor...

**Comment by donshin** [comment]
@spuky Thanks for the extensive debugging info- very helpful!

**Comment by SpencerBoyd** [comment]
This has been an issue since the original release. They just close the threads.

**Comment by donshin** [comment]
@SpencerBoyd Not sure if you saw the pull request referenced above- but that fix for this issue is scheduled to make it into the next Full Node Wallet release.
