### ISSUE TITLE
Error sending to Zaddress 

### ISSUE THREAD

**Issue by Skyryn** [BTCPrivate/bitcoin-private-full-node-wallet#29]
Sending from T to Z address error when using full node wallet

Error---> MSG
The Destination address to send BTCP to:
zk.....blabla
does not appear to be a valid BTCP address start with n1,nx or zz
Error END

All address I create using this full node wallet starts with zk
I Generated Z address using the same full node wallet
This may be a problem with sweeping as well 
Version 1.0.0 on Linux
We have three other nodes and they all generate a zk address not any of the address prefix listed in the error code.

**Comment by fokep** [comment]
Duplicate of #27 ?

**Comment by klove007** [comment]
possibly, unless they forgot to update to include the fix to the z addresses in 1.0.1

**Comment by Skyryn** [comment]
I did not see the update! that did fix it
Thanksl
