### ISSUE TITLE
Donation Addresses Missing

### ISSUE THREAD

**Issue by BleezInTheTrap** [BTCPrivate/bitcoin-private-full-node-wallet#35]
in the "About" write-up, both developers mentioned have no donation addresses listed. Add those in there, so that we can send you coins!
Thank you for putting this together

**Comment by fokep** [comment]
Coming in 1.0.2 :-)

`zkN1kCVEy7yNA8BrY8yZNYyLJKcMFs1nDALoXD9eTD3uSGn4jixv1pyYYoroEaKUyyhnkfC8gAm4wLMH2kx3WXgKduLo7eD`

ref. [Latest commit d8684e5](https://github.com/BTCPrivate/bitcoin-private-full-node-wallet/commit/d8684e5b6871a75cfc74021633345ea868363501#diff-6a102f61edd6c6f55d6f0ccb94832bf2)

**Comment by BleezInTheTrap** [comment]
sounds excellent, thanks!
