### ISSUE TITLE
Open ports?

### ISSUE THREAD

**Issue by irishismyname** [BTCPrivate/bitcoin-private-full-node-wallet#4]
Do we need to open any ports to accept peer connections? I'm only showing 1 connection and I'd guess that's the guy that's catching my node up to sync.

**Comment by fokep** [comment]
Yes, you need to accept TCP 7932 (RPC) / 7933 (P2P)

**Comment by irishismyname** [comment]
So 7933 should be open public, but 7932 should only be open to connect the wallet to the daemon correct?

**Comment by fokep** [comment]
Correct, 7933 for peer to peer.

RPC is optional. Default config is to only accept localhost.

`rpcallowip=127.0.0.1`

**Comment by irishismyname** [comment]
Many thanks.
