### ISSUE TITLE
OS High Sierra issue - Not opening

### ISSUE THREAD

**Issue by DLTech256** [BTCPrivate/bitcoin-private-full-node-wallet#5]
This error prompt occurs when trying to open- 
An unexpected error (Exception) has occurred:
com.ecliplesource.json.ParseException: Expected value at 1:1
See the console/logfile output for more detailed error information!

**Comment by lucianocn** [comment]
Same here - MaxOS Sierra 10.12.6
<img width="628" alt="123" src="https://user-images.githubusercontent.com/3828136/37244416-8afbf3b0-2467-11e8-8d44-8dc4010ab518.png">

**Comment by SpencerBoyd** [comment]
I had this error as well. You need to completely rebuild BTCP as described here (https://github.com/BTCPrivate/BitcoinPrivate) before you install the new wallet.

**Comment by lukevenediger** [comment]
Having the same problem. There must be an easier way than rebuilding BTCP.

**Comment by lukevenediger** [comment]
Can we get some attention on this issue please?

**Comment by MrGold86** [comment]
I followed the build instructions from https://github.com/BTCPrivate/BitcoinPrivate with this result (using macOS High Sierra Version 10.13.3):

xcode - select --install, and then /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
which ended with HEAD is now at 3cd5ae860 Merge pull request #3821 from rednoah/master

But when I run brew install cmake autoconf libtool automake coreutils pkgconfig gmp wget
it bombs:
/usr/local/bin/brew: line 9: /sw/sbin/readlink: Bad CPU type in executable
/usr/local/bin/brew: line 9: /sw/sbin/readlink: Bad CPU type in executable
/bin/bash: /usr/local/Library/Homebrew/brew.sh: No such file or directory
Failed during: /usr/local/bin/brew update --force
beamis@Wormwood:~/Library/Application Support/Zclassic >brew install cmake autoconf libtool automake coreutils pkgconfig gmp wget
/usr/local/bin/brew: line 9: /sw/sbin/readlink: Bad CPU type in executable
/usr/local/bin/brew: line 9: /sw/sbin/readlink: Bad CPU type in executable
/bin/bash: /usr/local/Library/Homebrew/brew.sh: No such file or directory
