### ISSUE TITLE
Error when starting GUI after downloading bootstrap.

### ISSUE THREAD

**Issue by sifotes** [BTCPrivate/bitcoin-private-full-node-wallet#7]
Windows 10

Downloaded the zip for windows, extracted, ran the .jar , everything was fine and the blockchain started syncing. Quit the gui, downloaded the bootstrap zip, extracted the folders to the appdata folder, opened the ran the .jar again. Now getting an popup error: 

![image](https://user-images.githubusercontent.com/26532668/36936832-34b01cfa-1ed8-11e8-913c-6bc5dff4e98b.png)

A reboot did not solve this.

Mentioned log files just shows the same error message:

> [Thread-85] [Sat Mar 03 11:44:58 EST 2018] [ERROR] Unexpected error:  
> com.vaklinov.zcashui.ZCashClientCaller$WalletCallException: Error response from wallet: error: couldn't connect to server: EOF reached (code 1)
> (make sure server is running and you are connecting to the correct RPC port)

**Comment by sifotes** [comment]
Running btcpd.exe manually and letting it sit for ~10 mins has partially fixed it. The GUI now shows "Daemo status: RUNNING" with 1 connection but the above error still comes up every ~30 seconds.

**Comment by sifotes** [comment]
Running btcpd.exe -reindex as suggested in #9 solved this issue. Think the issue should stay open for now.

**Comment by Pega88** [comment]
there was an issue with the 3.5GB download file, did you use that? Could you download the new file (6GB) and try to reproduce? should/could be fixed by that.

**Comment by sifotes** [comment]
I was using that originally. Wiped appdata clean, used the new bootstrap file and everything worked as expected. Can confirm the new file works without issue.
